name: Auto-Formatting

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint black isort autoflake
    - name: Analysing the code with pylint
      run: |
        black --line-length 88 $(git ls-files '*.py')
        isort --line-length 88 $(git ls-files '*.py') --profile black
        autoflake --in-place --remove-all-unused-imports -r $(git ls-files '*.py')
